---
- name: Create user and add to sudoers on Ubuntu systems
  hosts: all
  become: yes  # Run as sudo
  become_user: root
  vars:
    # These will be pulled from your Semaphore variable group
    username: "{{ username }}"
    password: "{{ password }}"
  tasks:
    - name: Install passlib on control node (run locally)
      pip:
        name: passlib
      delegate_to: localhost
      run_once: true
      become: no
    - name: Create user account
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        groups: sudo
        append: yes
        shell: /bin/bash
        createhome: yes
        state: present
    - name: Add user to sudoers file
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^{{ username }}"
        line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'
    - name: Ensure .ssh directory exists for user
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'
    - name: Add SSH public key to authorized_keys
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', 'ansible-key.pub') }}"
        path: "/home/{{ username }}/.ssh/authorized_keys"
    - name: Set proper permissions on home directory
      file:
        path: "/home/{{ username }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0755'
        state: directory
