---
- name: Update packages and check reboot requirements
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      register: cache_result
    
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
      register: upgrade_result
    
    - name: Check if system reboot is required
      ansible.builtin.stat:
        path: /run/reboot-required
      register: reboot_required
    
    - name: Report if reboot is required
      ansible.builtin.debug:
        msg: "Reboot is required"
      when: reboot_required.stat.exists
    
    - name: Send results to remote URL
      uri:
        url: "{{ remote_url }}"
        method: POST
        body_format: json
        body:
          hostname: "{{ inventory_hostname }}"
          timestamp: "{{ ansible_date_time.iso8601 }}"
          reboot_required: "{{ reboot_required.stat.exists }}"
          tasks:
            - name: "Update package cache"
              result: "{{ cache_result }}"
            - name: "Upgrade all packages"
              result: "{{ upgrade_result }}"
            - name: "Check reboot requirement"
              result: "{{ reboot_required }}"
        headers:
          Content-Type: "application/json"
      delegate_to: localhost
      become: no  # Don't use sudo for HTTP requests
      run_once: false
