---
- name: Update all packages on Debian-based systems
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      register: cache_result
    
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
      register: upgrade_result
    
    - name: Send results to remote URL
      uri:
        url: "{{ remote_url }}"
        method: POST
        body_format: json
        body:
          hostname: "{{ inventory_hostname }}"
          timestamp: "{{ ansible_date_time.iso8601 }}"
          tasks:
            - name: "Update package cache"
              result: "{{ cache_result }}"
            - name: "Upgrade all packages"
              result: "{{ upgrade_result }}"
        headers:
          Content-Type: "application/json"
      delegate_to: localhost
      run_once: false
