---
- name: Update and upgrade apt packages
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Kill any running apt processes
      shell: |
        killall apt apt-get dpkg >/dev/null 2>&1 || true
        killall unattended-upgrade >/dev/null 2>&1 || true
      ignore_errors: true
        
    - name: Remove apt locks if they exist
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/apt/lists/lock
        - /var/cache/apt/archives/lock
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend
      ignore_errors: true
      
    - name: Configure dpkg
      shell: dpkg --configure -a
      ignore_errors: true
      
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        update_cache: true
        
    - name: Upgrade packages with apt
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        upgrade: dist
