---
- name: Change user password on Ubuntu systems
  hosts: all
  become: yes  # Run as sudo
  become_user: root
  vars:
    # These will be pulled from your Semaphore variable group
    username: "{{ username }}"
    password: "{{ password }}"
  tasks:
    - name: Install passlib on control node (run locally)
      pip:
        name: passlib
      delegate_to: localhost
      run_once: true
      become: no
      
    - name: Check if user exists
      getent:
        database: passwd
        key: "{{ username }}"
      register: user_exists
      failed_when: false
      
    - name: Fail if user does not exist
      fail:
        msg: "User {{ username }} does not exist on the system"
      when: user_exists.failed
      
    - name: Change user password
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        update_password: always
        state: present
        
    - name: Force password change on next login (optional)
      shell: "chage -d 0 {{ username }}"
      when: force_password_change | default(false) | bool
